image: node:10

stages:
  - quality

lint:
  stage: quality
  only:
    refs:
      - tags
      - master
      - testing
      - next
      - merge_requests
  script:
    - npm ci
    - npm run lint
